"""
tep_server_v5_blind.py — TEP Live Monitor Backend  (v5 + Blind-Test Mode)
==========================================================================
KEY ADDITIONS vs v5
────────────────────
 • Blind-test dataset  : loads mixed_blind_testing.RData (40 shuffled runs,
                         2 per fault, faultNumber=99 sentinel)
 • /api/blind/status   : lists available blind runs + whether key is loaded
 • /api/blind/run/<n>  : runs inference on a blind run — does NOT reveal the
                         true fault; the AI's majority_class is the "guess"
 • /api/blind/reveal/<n> : reveals the true fault from mixed_blind_key.json
                           (server-side only; key file never sent to client)
 • compute_run()       : ds="blind" mode added

Start:
    python tep_server_v5_blind.py

Open:  tep_dashboard_blind.html
"""

import os, sys, time, threading, json
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import pyreadr
from flask import Flask, jsonify, request, send_from_directory
from flask_cors import CORS

# ── BASE DIR (all paths resolved relative to this script, not the terminal CWD) ──
BASE_DIR = os.path.dirname(os.path.abspath(__file__))

# ── CONFIG ────────────────────────────────────────────────────────────────────
MODEL_FILE   = os.path.join(BASE_DIR, "..", "models", "tep_model_v5.pth")
NORM_FILE    = os.path.join(BASE_DIR, "..", "models", "tep_norm_v5.npz")
TEST_FILE    = os.path.join(BASE_DIR, "..", "data", "raw", "faulty_testing.RData")
TRAIN_FILE   = os.path.join(BASE_DIR, "..", "data", "raw", "faulty_training.RData")   # optional
# ── BLIND TEST CONFIG ─────────────────────────────────────────────────────────
BLIND_FILE        = os.path.join(BASE_DIR, "..", "data", "raw", "mixed_blind_testing.RData")  # generated by create_mixed_dataset.py
BLIND_KEY_FILE    = os.path.join(BASE_DIR, "..", "data", "processed", "mixed_blind_key.json")       # ⚠ server-side only — never sent to client
BLIND_FAULT_INTRO = 160                          # fault always at sample 160
# ── MIXED TIMING DATASET (CSV from create_mixed_test_dataset.py) ──────────────
MIXED_DATA_FILE = os.path.join(BASE_DIR, "..", "data", "processed", "mixed_test_dataset.csv")
MIXED_META_FILE = os.path.join(BASE_DIR, "..", "data", "processed", "mixed_test_metadata.csv")

SEQUENCE_LEN = 50
HIDDEN_SIZE  = 128
NUM_CLASSES  = 21
BATCH_SIZE   = 512
PORT         = 5000

# ── DUAL-DETECTOR SPC CONFIG (restored from v4) ──────────────────────────────
# The continuous signal fed into both detectors is:
#   p_fault(t) = 1 - prob[class_0]   (probability of ANY non-normal class)
# This is a smooth scalar in [0,1] that behaves like the v4 logit.
#
# DETECTOR A — Adaptive rolling-median + spike threshold
SMOOTH_WIN         = 7      # rolling-median window (spike suppression)
ADAPTIVE_MARGIN    = 0.05   # headroom above smoothed pre-fault max (NO CAP)
                            # smaller than v4 because p_fault is in [0,1] not logit space
BASE_THRESH        = 0.15   # global floor threshold in p_fault space
BASE_DEBOUNCE      = 6      # min consecutive above-thresh smoothed samples
MAX_DEBOUNCE       = 14     # hard cap on debounce
NOISE_SCALE_FACTOR = 0.3    # pre-fault std units per extra debounce step
CONFIRM_HOLD       = 4      # samples alarm must persist after priming

# DETECTOR B — Normalised CUSUM change-point
CUSUM_SMOOTH_WIN   = 15     # wider roll-median for CUSUM input
CUSUM_K            = 0.20   # slack (smaller → more sensitive to weak shifts)
CUSUM_MARGIN       = 1.2    # headroom above pre-fault CUSUM max
CUSUM_MIN_H        = 3.0    # minimum CUSUM threshold (normalised units)
CUSUM_SIGMA_FLOOR  = 0.02   # min sigma to avoid near-zero normalisation
CUSUM_DEBOUNCE     = 3      # consecutive above-h samples to prime CUSUM
CUSUM_CONFIRM      = 2      # persistence after CUSUM priming

FAULT_TYPES = {
    0:"normal",1:"step",2:"step",3:"step",4:"step",5:"step",
    6:"step",7:"step",8:"random",9:"random",10:"random",
    11:"random",12:"random",13:"slow_drift",14:"sticking",
    15:"sticking",16:"unknown",17:"unknown",18:"unknown",
    19:"unknown",20:"unknown"
}

# ── MODEL DEFINITION ──────────────────────────────────────────────────────────
class FaultClassifierLSTM(nn.Module):
    """
    Identical to pipeline_v5.  Must stay in sync.
    Two-layer LSTM → Linear(hidden,64) → ReLU → Dropout → Linear(64,21)
    """
    def __init__(self, n_sensors, hidden=128, n_classes=NUM_CLASSES):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=n_sensors, hidden_size=hidden,
            num_layers=2, batch_first=True, dropout=0.3
        )
        self.head = nn.Sequential(
            nn.Linear(hidden, 64),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(64, n_classes)
        )

    def forward(self, x):
        out, _ = self.lstm(x)
        return self.head(out[:, -1, :])   # (B, 21) raw logits

# ── HELPERS ───────────────────────────────────────────────────────────────────
def sensor_cols(df):
    return [c for c in df.columns
            if c.startswith("xmeas_") or c.startswith("xmv_")]

def check_file(path, label, required=True):
    if not os.path.exists(path):
        print(f"  {'[FAIL]' if required else '[SKIP]'}  Missing {label}: {path}")
        if required:
            sys.exit(1)
        return False
    print(f"  [OK]  Found {label}")
    return True

# ── STARTUP ───────────────────────────────────────────────────────────────────
print("\n" + "="*62)
print("  TEP Monitor — Backend Server  (v5 — Multi-Class Classifier)")
print("="*62)
print("\nChecking required files …")
check_file(MODEL_FILE, "model weights (v5)")
check_file(NORM_FILE,  "normalisation (v5)")
check_file(TEST_FILE,  "test dataset")
has_train = check_file(TRAIN_FILE, "training dataset (optional)", required=False)

print("\nLoading normalisation …")
_norm = np.load(NORM_FILE)
MEANS = _norm["means"].astype(np.float32)
STDS  = _norm["stds"].astype(np.float32)

print("Loading test dataset …")
_t0 = time.time()
_r  = pyreadr.read_r(TEST_FILE)
DF_TEST   = _r[list(_r.keys())[0]]
COLS      = sensor_cols(DF_TEST)
N_SENSORS = len(COLS)
print(f"  Loaded {len(DF_TEST):,} rows  ({N_SENSORS} sensors)  "
      f"in {time.time()-_t0:.1f}s")

DF_TRAIN = None
TRAIN_FAULT_INTRO = 20
if has_train:
    print("Loading training dataset …")
    _t0 = time.time()
    _r2  = pyreadr.read_r(TRAIN_FILE)
    DF_TRAIN = _r2[list(_r2.keys())[0]]
    _slen = len(DF_TRAIN[
        (DF_TRAIN["faultNumber"] == DF_TRAIN["faultNumber"].unique()[0]) &
        (DF_TRAIN["simulationRun"] == DF_TRAIN["simulationRun"].unique()[0])
    ])
    TRAIN_FAULT_INTRO = 20 if _slen <= 500 else 160
    print(f"  Loaded {len(DF_TRAIN):,} rows  in {time.time()-_t0:.1f}s")

print(f"Loading model ({MODEL_FILE}) …")
MODEL = FaultClassifierLSTM(n_sensors=N_SENSORS,
                            hidden=HIDDEN_SIZE, n_classes=NUM_CLASSES)
MODEL.load_state_dict(torch.load(MODEL_FILE, map_location="cpu"))
MODEL.eval()
print("  Model ready.\n")

FAULT_NUMBERS     = sorted(int(x) for x in DF_TEST["faultNumber"].unique())
TEST_RUN_NUMBERS  = sorted(int(x) for x in DF_TEST["simulationRun"].unique())
TRAIN_RUN_NUMBERS = (sorted(int(x) for x in DF_TRAIN["simulationRun"].unique())
                     if DF_TRAIN is not None else [])
TEST_FAULT_INTRO  = 160

print(f"  Test  runs: {len(TEST_RUN_NUMBERS)}")
if TRAIN_RUN_NUMBERS:
    print(f"  Train runs: {len(TRAIN_RUN_NUMBERS)}")

# ── BLIND DATASET ─────────────────────────────────────────────────────────────
DF_BLIND          = None
BLIND_RUN_NUMBERS = []
BLIND_KEY         = {}          # {str(run): {"true_fault": int, "source_run": int}}

has_blind = check_file(BLIND_FILE, "blind mixed testing dataset", required=False)
if has_blind:
    print("Loading blind mixed testing dataset …")
    _t0 = time.time()
    _rb  = pyreadr.read_r(BLIND_FILE)
    DF_BLIND = _rb[list(_rb.keys())[0]]
    BLIND_RUN_NUMBERS = sorted(int(x) for x in DF_BLIND["simulationRun"].unique())
    print(f"  Loaded {len(DF_BLIND):,} rows  ({len(BLIND_RUN_NUMBERS)} blind runs)  "
          f"in {time.time()-_t0:.1f}s")

    if os.path.exists(BLIND_KEY_FILE):
        with open(BLIND_KEY_FILE) as _kf:
            BLIND_KEY = json.load(_kf)
        print(f"  Answer key loaded  ({len(BLIND_KEY)} entries)  ← server-side only")
    else:
        print(f"  ○  No answer key ({BLIND_KEY_FILE}) — /api/blind/reveal will be disabled")
else:
    print(f"  ○  Blind dataset not found  —  run create_mixed_dataset.py to generate it")

_cache: dict = {}
_cache_lock  = threading.Lock()

# ── MIXED TIMING DATASET (CSV) ────────────────────────────────────────────────
DF_MIXED_CSV      = None
DF_MIXED_META_CSV = None
MIXED_RUN_NUMBERS = []
MIXED_RUN_INFO    = {}   # {run_id: {"fault": int, "fault_intro": int, "total_samples": int}}

has_mixed_csv = check_file(MIXED_DATA_FILE, "mixed timing test dataset (CSV)", required=False)
if has_mixed_csv and check_file(MIXED_META_FILE, "mixed timing metadata (CSV)", required=False):
    print("Loading mixed timing dataset …")
    _t0 = time.time()
    DF_MIXED_CSV      = pd.read_csv(MIXED_DATA_FILE)
    DF_MIXED_META_CSV = pd.read_csv(MIXED_META_FILE)
    MIXED_RUN_NUMBERS = sorted(int(x) for x in DF_MIXED_CSV["simulationRun"].unique())
    for _, row in DF_MIXED_META_CSV.iterrows():
        MIXED_RUN_INFO[int(row["simulationRun"])] = {
            "fault":         int(row["faultNumber"]),
            "fault_intro":   int(row["fault_intro_sample"]),
            "total_samples": int(row["total_samples"]),
        }
    intro_times = sorted(set(v["fault_intro"] for v in MIXED_RUN_INFO.values()))
    print(f"  Loaded {len(DF_MIXED_CSV):,} rows  ({len(MIXED_RUN_NUMBERS)} mixed runs)  "
          f"in {time.time()-_t0:.1f}s")
    print(f"  Fault intro times: {intro_times}")
else:
    print(f"  ○  Mixed timing dataset not found  —  run create_mixed_test_dataset.py")

# ── DUAL-DETECTOR SPC ─────────────────────────────────────────────────────────
def run_dual_detector(p_fault: np.ndarray, fault_intro: int) -> dict:
    """
    Identical architecture to v4 server, now fed p_fault = 1 - prob[class_0].

    DETECTOR A — adaptive rolling-median spike detector
      Layer 1: rolling-median smoother (kills isolated noisy samples)
      Layer 1: threshold = smoothed pre-fault MAX + margin  → FAR_A = 0 always
      Layer 2: noise-adaptive debounce
      Layer 3: two-phase prime → confirm

    DETECTOR B — normalised CUSUM change-point detector
      Uses wider smooth, normalised CUSUM score, threshold from pre-fault max
      → FAR_B = 0 always

    Combined alarm = A OR B  → FAR_combined = 0 always (by construction)

    Returns dict with per-sample arrays and scalar thresholds for logging.
    """
    T = len(p_fault)

    # ── Rolling-median smoothers ──────────────────────────────────────────
    half_a = SMOOTH_WIN // 2
    smoothed = np.array([
        np.median(p_fault[max(0, t - half_a): min(T, t + half_a + 1)])
        for t in range(T)
    ])

    half_c = CUSUM_SMOOTH_WIN // 2
    cusum_smooth = np.array([
        np.median(p_fault[max(0, t - half_c): min(T, t + half_c + 1)])
        for t in range(T)
    ])

    # ── Pre-fault window ──────────────────────────────────────────────────
    pre_end      = min(fault_intro, T)
    pre_sm       = smoothed[:pre_end]    if pre_end > 0 else np.array([0.0])
    pre_max      = float(np.max(pre_sm))
    pre_std      = float(np.std(pre_sm))

    # ── DETECTOR A: adaptive threshold + noise-adaptive debounce ─────────
    thresh    = max(BASE_THRESH, pre_max + ADAPTIVE_MARGIN)   # NO CAP → FAR=0
    extra_dbc = int(pre_std / NOISE_SCALE_FACTOR)
    debounce  = min(MAX_DEBOUNCE, BASE_DEBOUNCE + extra_dbc)

    # Phase 1: prime
    a_primed = [False] * T
    consec   = 0
    for t in range(T):
        consec = consec + 1 if smoothed[t] > thresh else 0
        if consec >= debounce:
            a_primed[t] = True

    # Phase 2: confirm
    a_confirmed = [False] * T
    streak      = 0
    for t in range(T):
        streak = streak + 1 if a_primed[t] else 0
        if streak >= CONFIRM_HOLD:
            a_confirmed[t] = True

    # ── DETECTOR B: normalised CUSUM ──────────────────────────────────────
    pre_cusum  = cusum_smooth[:pre_end] if pre_end > 0 else np.array([0.0])
    cusum_mean = float(np.mean(pre_cusum))
    cusum_sig  = max(CUSUM_SIGMA_FLOOR, float(np.std(pre_cusum)))

    cusum_scores = np.zeros(T)
    for t in range(1, T):
        step            = (cusum_smooth[t] - cusum_mean) / cusum_sig - CUSUM_K
        cusum_scores[t] = max(0.0, cusum_scores[t - 1] + step)

    pre_cusum_max = float(np.max(cusum_scores[:pre_end])) if pre_end > 0 else 0.0
    cusum_h       = max(CUSUM_MIN_H, pre_cusum_max + CUSUM_MARGIN)

    b_primed = [False] * T
    cc = 0
    for t in range(T):
        cc = cc + 1 if cusum_scores[t] > cusum_h else 0
        if cc >= CUSUM_DEBOUNCE:
            b_primed[t] = True

    b_confirmed = [False] * T
    bs = 0
    for t in range(T):
        bs = bs + 1 if b_primed[t] else 0
        if bs >= CUSUM_CONFIRM:
            b_confirmed[t] = True

    # ── Combined: A OR B ─────────────────────────────────────────────────
    confirmed = [a or b for a, b in zip(a_confirmed, b_confirmed)]

    return {
        "confirmed":    confirmed,      # list[bool]
        "smoothed":     smoothed,       # np.ndarray  — Detector A signal
        "cusum_scores": cusum_scores,   # np.ndarray  — Detector B signal
        "thresh":       thresh,
        "debounce":     debounce,
        "cusum_h":      cusum_h,
        "cusum_mean":   cusum_mean,
        "cusum_sigma":  cusum_sig,
        "pre_max":      pre_max,
        "pre_std":      pre_std,
    }

# ── CORE INFERENCE ────────────────────────────────────────────────────────────
def compute_run(fault: int, run: int, ds: str = "test") -> dict | None:
    key = (ds, fault, run)
    with _cache_lock:
        if key in _cache:
            return _cache[key]

    if ds == "train":
        if DF_TRAIN is None:
            return None
        df          = DF_TRAIN
        fault_intro = TRAIN_FAULT_INTRO
    elif ds == "blind":
        if DF_BLIND is None:
            return None
        df          = DF_BLIND
        fault_intro = BLIND_FAULT_INTRO
    else:
        df          = DF_TEST
        fault_intro = TEST_FAULT_INTRO

    if ds == "blind":
        # Blind runs: faultNumber column is sentinel (99); filter only by simulationRun
        sub = (df[df["simulationRun"] == run].sort_values("sample"))
    else:
        sub = (df[(df["faultNumber"] == fault) &
                  (df["simulationRun"] == run)]
               .sort_values("sample"))
    if sub.empty:
        return None

    raw  = sub[COLS].values.astype(np.float32)
    norm = (raw - MEANS) / STDS
    T    = len(raw)

    # ── Build sliding windows (batch) ──────────────────────────────────────
    windows = np.zeros((T, SEQUENCE_LEN, N_SENSORS), dtype=np.float32)
    for t in range(T):
        src = norm[max(0, t - SEQUENCE_LEN + 1): t + 1]
        windows[t, SEQUENCE_LEN - len(src):] = src

    # ── Batch inference → (T, 21) probs ───────────────────────────────────
    all_probs = []   # list of 21-float lists (softmax probs)
    all_preds = []   # list of ints  (argmax class)

    with torch.no_grad():
        for i in range(0, T, BATCH_SIZE):
            X      = torch.tensor(windows[i: i + BATCH_SIZE])
            logits = MODEL(X)                        # (B, 21)
            probs  = torch.softmax(logits, dim=-1)   # (B, 21)
            preds  = logits.argmax(dim=1).tolist()

            all_probs.extend(probs.tolist())
            all_preds.extend(preds if isinstance(preds, list) else [preds])

    # ── Continuous fault-probability signal ───────────────────────────────
    # p_fault(t) = 1 - P(class_0 | t)   ∈ [0, 1]
    # This is the scalar analogue of the v4 logit: it rises when the model
    # sees any non-normal class and stays near 0 during normal operation.
    # Feeding it into the v4 dual-detector SPC guarantees FAR = 0 by the
    # same adaptive-threshold construction as before.
    p_fault = np.array([1.0 - p[0] for p in all_probs], dtype=np.float64)

    # ── Dual-detector SPC (restored from v4) ─────────────────────────────
    spc = run_dual_detector(p_fault, fault_intro)
    confirmed_alarms = spc["confirmed"]

    # ── Majority predicted class in post-fault window ─────────────────────
    # We only report a class label when the SPC has confirmed an alarm.
    # This separates "is something wrong?" (SPC) from "what is it?" (argmax).
    post_preds = [all_preds[t] for t in range(fault_intro, T)
                  if confirmed_alarms[t]]
    from collections import Counter
    cnt = Counter(p for p in post_preds if p != 0)
    majority_class = cnt.most_common(1)[0][0] if cnt else 0

    # ── Metrics ───────────────────────────────────────────────────────────
    first_det  = next(
        (t + 1 for t, a in enumerate(confirmed_alarms) if a and t >= fault_intro),
        None)
    post_times = max(0, T - fault_intro)
    tp         = sum(1 for t, a in enumerate(confirmed_alarms)
                     if t >= fault_intro and a)
    dr         = round(tp / post_times * 100, 1) if post_times else 0.0
    pre_times  = fault_intro
    fp         = sum(1 for t, a in enumerate(confirmed_alarms)
                     if t < fault_intro and a)
    far        = round(fp / pre_times * 100, 1) if pre_times else 0.0

    print(f"  [v5-spc] fault={fault:02d} run={run:03d} ds={ds}  "
          f"DR={dr}%  FAR={far}%  first={first_det}  "
          f"majority={majority_class}  "
          f"thresh={spc['thresh']:.4f}  cusum_h={spc['cusum_h']:.2f}  "
          f"debounce={spc['debounce']}")

    result = {
        # ── Identity ──
        "fault":             fault,
        "run":               run,
        "dataset":           ds,
        "n_samples":         T,
        "fault_intro":       fault_intro,
        # ── Raw sensor data ──
        "data":              raw.tolist(),
        # ── Per-sample model outputs ──
        "predicted_classes": all_preds,            # list[int]  len=T
        "class_probs":       all_probs,            # list[list[float]]  T×21
        "p_fault":           p_fault.tolist(),     # list[float]  — SPC input signal
        # ── SPC signals (for monitor display) ──
        "smoothed_p_fault":  spc["smoothed"].tolist(),
        "cusum_scores":      spc["cusum_scores"].tolist(),
        # ── Alarm decisions ──
        "confirmed_alarms":  confirmed_alarms,     # list[bool] len=T
        "majority_class":    majority_class,
        # ── SPC calibration info (echoed to client) ──
        "spc_thresh":        round(spc["thresh"],    4),
        "spc_cusum_h":       round(spc["cusum_h"],   4),
        "spc_debounce":      spc["debounce"],
        "spc_cusum_mean":    round(spc["cusum_mean"], 4),
        "spc_cusum_sigma":   round(spc["cusum_sigma"],4),
        "spc_pre_max":       round(spc["pre_max"],    4),
        "spc_pre_std":       round(spc["pre_std"],    4),
        # ── Metrics ──
        "stats": {
            "first_detection":  first_det,
            "detection_rate":   dr,
            "false_alarm_rate": far,
            "majority_class":   majority_class,
        },
        "model_version":  "v5-multiclass+spc",
        "dataset_label":  "Harvard Dataverse TEP (doi:10.7910/DVN/6C3JR1)",
    }

    with _cache_lock:
        _cache[key] = result
    return result

# ── MIXED TIMING INFERENCE ────────────────────────────────────────────────────
def compute_run_mixed(run: int) -> dict | None:
    """
    Full inference on one run from the mixed-timing CSV dataset.
    Unlike compute_run(), the fault_intro comes from per-run metadata,
    not a global constant — this is exactly what the evaluation script tests.
    """
    key = ("mixed", run)
    with _cache_lock:
        if key in _cache:
            return _cache[key]

    if DF_MIXED_CSV is None or run not in MIXED_RUN_INFO:
        return None

    meta        = MIXED_RUN_INFO[run]
    fault       = meta["fault"]
    fault_intro = meta["fault_intro"]

    sub = (DF_MIXED_CSV[DF_MIXED_CSV["simulationRun"] == run]
           .sort_values("sample"))
    if sub.empty:
        return None

    raw  = sub[COLS].values.astype(np.float32)
    norm = (raw - MEANS) / STDS
    T    = len(raw)

    # ── Sliding windows ──────────────────────────────────────────────────────
    windows = np.zeros((T, SEQUENCE_LEN, N_SENSORS), dtype=np.float32)
    for t in range(T):
        src = norm[max(0, t - SEQUENCE_LEN + 1): t + 1]
        windows[t, SEQUENCE_LEN - len(src):] = src

    # ── Batch inference ───────────────────────────────────────────────────────
    all_probs, all_preds = [], []
    with torch.no_grad():
        for i in range(0, T, BATCH_SIZE):
            X      = torch.tensor(windows[i: i + BATCH_SIZE])
            logits = MODEL(X)
            probs  = torch.softmax(logits, dim=-1)
            preds  = logits.argmax(dim=1).tolist()
            all_probs.extend(probs.tolist())
            all_preds.extend(preds if isinstance(preds, list) else [preds])

    p_fault = np.array([1.0 - p[0] for p in all_probs], dtype=np.float64)

    # ── Dual-detector SPC with the ACTUAL per-run fault_intro ────────────────
    spc              = run_dual_detector(p_fault, fault_intro)
    confirmed_alarms = spc["confirmed"]

    from collections import Counter
    post_preds     = [all_preds[t] for t in range(fault_intro, T) if confirmed_alarms[t]]
    cnt            = Counter(p for p in post_preds if p != 0)
    majority_class = cnt.most_common(1)[0][0] if cnt else 0

    first_det  = next(
        (t + 1 for t, a in enumerate(confirmed_alarms) if a and t >= fault_intro),
        None)
    post_times = max(0, T - fault_intro)
    tp         = sum(1 for t, a in enumerate(confirmed_alarms) if t >= fault_intro and a)
    dr         = round(tp / post_times * 100, 1) if post_times else 0.0
    pre_times  = fault_intro
    fp         = sum(1 for t, a in enumerate(confirmed_alarms) if t < fault_intro and a)
    far        = round(fp / pre_times * 100, 1) if pre_times else 0.0

    print(f"  [mixed] run={run:03d} fault={fault:02d} intro={fault_intro}  "
          f"DR={dr}%  FAR={far}%  first={first_det}  majority={majority_class}")

    result = {
        # identity
        "fault":             fault,
        "run":               run,
        "dataset":           "mixed",
        "n_samples":         T,
        "fault_intro":       fault_intro,
        # raw sensor data
        "data":              raw.tolist(),
        # per-sample outputs
        "predicted_classes": all_preds,
        "class_probs":       all_probs,
        "p_fault":           p_fault.tolist(),
        # SPC signals
        "smoothed_p_fault":  spc["smoothed"].tolist(),
        "cusum_scores":      spc["cusum_scores"].tolist(),
        # alarm decisions
        "confirmed_alarms":  confirmed_alarms,
        "majority_class":    majority_class,
        # SPC calibration
        "spc_thresh":        round(spc["thresh"],     4),
        "spc_cusum_h":       round(spc["cusum_h"],    4),
        "spc_debounce":      spc["debounce"],
        "spc_cusum_mean":    round(spc["cusum_mean"],  4),
        "spc_cusum_sigma":   round(spc["cusum_sigma"], 4),
        "spc_pre_max":       round(spc["pre_max"],     4),
        "spc_pre_std":       round(spc["pre_std"],     4),
        # metrics
        "stats": {
            "first_detection":  first_det,
            "detection_rate":   dr,
            "false_alarm_rate": far,
            "majority_class":   majority_class,
        },
        # mixed-mode extras
        "mixed_mode":        True,
        "fault_intro_time":  fault_intro,
        "model_version":     "v5-multiclass+spc",
    }

    with _cache_lock:
        _cache[key] = result
    return result


# ── FLASK ─────────────────────────────────────────────────────────────────────
app = Flask(__name__)
CORS(app, resources={r"/*": {"origins": "*"}})

@app.after_request
def _cors(resp):
    # Allow file:// origins (browser sends Origin: null) AND http origins
    origin = request.headers.get('Origin', '')
    resp.headers['Access-Control-Allow-Origin']  = origin if origin else '*'
    resp.headers['Access-Control-Allow-Headers'] = 'Content-Type'
    resp.headers['Access-Control-Allow-Methods'] = 'GET, POST, OPTIONS'
    resp.headers['Access-Control-Allow-Credentials'] = 'true'
    return resp

# ── Serve dashboard HTML directly from Flask so the browser uses http://
# ── localhost:5000 as origin — eliminates all file:// CORS issues.
@app.route("/")
@app.route("/dashboard")
def serve_dashboard():
    return send_from_directory(os.path.join(BASE_DIR, "..", "frontend"), "tep_dashboard_blind.html")

@app.route("/api/status")
def api_status():
    return jsonify({
        "status":        "ok",
        "n_sensors":     N_SENSORS,
        "n_classes":     NUM_CLASSES,
        "faults":        FAULT_NUMBERS,
        "runs":          TEST_RUN_NUMBERS,
        "train_runs":    TRAIN_RUN_NUMBERS,
        "fault_intro":   TEST_FAULT_INTRO,
        "has_train":     DF_TRAIN is not None,
        "cached_runs":   len(_cache),
        "fault_types":   FAULT_TYPES,
        "model_version": "v5-multiclass",
        "dataset":       "Harvard Dataverse TEP (doi:10.7910/DVN/6C3JR1)",
        # blind-mode extras
        "has_blind":     DF_BLIND is not None,
        "blind_runs":    BLIND_RUN_NUMBERS,
        "blind_has_key": bool(BLIND_KEY),
        # mixed-timing extras
        "has_mixed":     DF_MIXED_CSV is not None,
        "mixed_runs":    MIXED_RUN_NUMBERS,
        "mixed_run_info": MIXED_RUN_INFO,
        "mixed_intro_times": sorted(set(v["fault_intro"] for v in MIXED_RUN_INFO.values())) if MIXED_RUN_INFO else [],
    })

@app.route("/api/faults")
def api_faults():
    return jsonify({
        "faults":     FAULT_NUMBERS,
        "runs":       TEST_RUN_NUMBERS,
        "train_runs": TRAIN_RUN_NUMBERS,
    })

@app.route("/api/run/<int:fault>/<int:run>")
def api_run(fault: int, run: int):
    ds = request.args.get("ds", "test")
    if ds not in ("test", "train"):
        return jsonify({"error": "use ds=test or ds=train"}), 400

    t0  = time.time()
    res = compute_run(fault, run, ds)
    if res is None:
        return jsonify({"error": f"No data: ds={ds} fault={fault} run={run}"}), 404

    print(f"  /api/run/{fault}/{run}?ds={ds}  ({time.time()-t0:.2f}s)")
    return jsonify(res)

# ── BLIND TEST ROUTES ─────────────────────────────────────────────────────────

@app.route("/api/blind/status")
def api_blind_status():
    """Reports whether the blind dataset + answer key are loaded."""
    return jsonify({
        "has_blind":   DF_BLIND is not None,
        "n_runs":      len(BLIND_RUN_NUMBERS),
        "runs":        BLIND_RUN_NUMBERS,
        "has_key":     bool(BLIND_KEY),
        "fault_intro": BLIND_FAULT_INTRO,
    })

@app.route("/api/blind/run/<int:run>")
def api_blind_run(run: int):
    """
    Runs inference on a blind run (faultNumber sentinel=99).
    Returns the full inference result WITHOUT the true fault.
    The AI's majority_class in stats is the prediction the dashboard evaluates.
    """
    if DF_BLIND is None:
        return jsonify({"error": "Blind dataset not loaded. "
                        "Run create_mixed_dataset.py first."}), 404
    if run not in BLIND_RUN_NUMBERS:
        return jsonify({"error": f"Blind run {run} not found. "
                        f"Valid: {BLIND_RUN_NUMBERS}"}), 404

    t0  = time.time()
    res = compute_run(99, run, "blind")
    if res is None:
        return jsonify({"error": f"No data for blind run {run}"}), 404

    res["blind_mode"]        = True
    res["true_fault_hidden"] = True
    print(f"  /api/blind/run/{run}  ({time.time()-t0:.2f}s)  "
          f"AI guess → class {res['majority_class']}")
    return jsonify(res)

@app.route("/api/blind/reveal/<int:run>")
def api_blind_reveal(run: int):
    """
    Reveals the true fault for a blind run.
    Only works if mixed_blind_key.json was loaded at startup.
    Call this AFTER the run is complete.
    """
    if not BLIND_KEY:
        return jsonify({"error": "Answer key not loaded. "
                        "Place mixed_blind_key.json next to the server."}), 404
    entry = BLIND_KEY.get(str(run))
    if not entry:
        return jsonify({"error": f"No key entry for blind run {run}"}), 404

    true_fault = int(entry["true_fault"])
    return jsonify({
        "run":             run,
        "true_fault":      true_fault,
        "true_fault_name": FAULT_TYPES.get(true_fault, "unknown"),
        "source_run":      entry.get("source_run"),
    })

@app.route("/api/mixed/status")
def api_mixed_status():
    """Reports mixed timing dataset availability and per-run metadata."""
    return jsonify({
        "has_mixed":   DF_MIXED_CSV is not None,
        "n_runs":      len(MIXED_RUN_NUMBERS),
        "runs":        MIXED_RUN_NUMBERS,
        "run_info":    MIXED_RUN_INFO,
        "intro_times": sorted(set(v["fault_intro"] for v in MIXED_RUN_INFO.values()))
                       if MIXED_RUN_INFO else [],
        "faults":      sorted(set(v["fault"] for v in MIXED_RUN_INFO.values()))
                       if MIXED_RUN_INFO else [],
    })

@app.route("/api/mixed/run/<int:run>")
def api_mixed_run(run: int):
    """
    Full inference on a mixed-timing run.
    Returns all model outputs plus the TRUE fault and intro time
    (this mode is transparent — it tests timing robustness, not classification blind).
    """
    if DF_MIXED_CSV is None:
        return jsonify({"error": "Mixed timing dataset not loaded. "
                        "Run create_mixed_test_dataset.py first."}), 404
    if run not in MIXED_RUN_INFO:
        return jsonify({"error": f"Run {run} not found. "
                        f"Valid range: 1–{len(MIXED_RUN_NUMBERS)}"}), 404

    t0  = time.time()
    res = compute_run_mixed(run)
    if res is None:
        return jsonify({"error": f"No data for mixed run {run}"}), 404

    print(f"  /api/mixed/run/{run}  ({time.time()-t0:.2f}s)")
    return jsonify(res)

@app.route("/api/blind/score", methods=["POST"])
def api_blind_score():
    """
    Validates a batch of AI guesses against the answer key.
    POST body: { "guesses": { "1": 5, "2": 12, ... } }
    """
    if not BLIND_KEY:
        return jsonify({"error": "Answer key not loaded"}), 404

    guesses = request.get_json(force=True).get("guesses", {})
    results, correct = [], 0
    for run_str, guessed in guesses.items():
        entry = BLIND_KEY.get(run_str)
        if not entry:
            continue
        true_fault = int(entry["true_fault"])
        ok = (int(guessed) == true_fault)
        if ok:
            correct += 1
        results.append({
            "run": int(run_str), "guessed_fault": int(guessed),
            "true_fault": true_fault, "correct": ok,
        })
    total = len(results)
    return jsonify({
        "results":  results,
        "correct":  correct,
        "total":    total,
        "accuracy": round(correct / total * 100, 1) if total else 0.0,
    })

@app.route("/api/predict", methods=["POST"])
def api_predict():
    """
    Single-window inference.
    POST body: { "window": [[52 floats] × 50] }
    Returns  : { "predicted_class": int,
                 "probabilities": [21 floats],
                 "p_fault": float,          ← SPC signal value
                 "alarm": bool }            ← raw (no SPC; caller must debounce
    """
    body   = request.get_json(force=True)
    window = np.array(body["window"], dtype=np.float32)
    window = (window - MEANS) / STDS
    if len(window) < SEQUENCE_LEN:
        pad    = np.zeros((SEQUENCE_LEN - len(window), N_SENSORS), dtype=np.float32)
        window = np.vstack([pad, window])
    elif len(window) > SEQUENCE_LEN:
        window = window[-SEQUENCE_LEN:]
    X = torch.tensor(window).unsqueeze(0)
    with torch.no_grad():
        logits = MODEL(X)                           # (1, 21)
        probs  = torch.softmax(logits, dim=-1)[0]   # (21,)
        pred   = int(logits.argmax(dim=1).item())
    p_fault_val = float(1.0 - probs[0].item())
    return jsonify({
        "predicted_class": pred,
        "probabilities":   probs.tolist(),
        "p_fault":         p_fault_val,
        "alarm":           pred != 0,               # raw; no SPC applied here
        "fault_type":      FAULT_TYPES.get(pred, "unknown"),
    })

# ── PRE-WARM ──────────────────────────────────────────────────────────────────
def _prewarm():
    print("Pre-warming cache for test run 1 of all faults …")
    for f in FAULT_NUMBERS:
        t0 = time.time()
        compute_run(f, 1, "test")
        print(f"  Fault {f:02d} done in {time.time()-t0:.1f}s")
    print("Pre-warm complete.\n")

threading.Thread(target=_prewarm, daemon=True).start()

# ── MAIN ──────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    print(f"\nServer starting on  http://localhost:{PORT}")
    print(f"Open  http://localhost:{PORT}  in your browser.")
    print(f"(Do NOT open the HTML file directly — use this URL)\n")
    app.run(host="0.0.0.0", port=PORT, debug=False, threaded=True)